---
- name: Add Nodejs source to apt source list
  shell: >
    curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash
- name: Install nodejs 4.x
  apt: name=nodejs=4.* state=present
  sudo: yes
